# This is the 1Password SSH agent config file, which allows you to customize the
# behavior of the SSH agent running on this machine.
#
# You can use it to:
# * Enable keys from other vaults than the Private vault
# * Control the order in which keys are offered to SSH servers
#
# EXAMPLE
#
# By default, all keys in your Private vault(s) are enabled:
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can enable more keys by adding more `[[ssh-keys]]` entries.
# For example, to first enable item "My SSH Key" from "My Custom Vault":
#
#  [[ssh-keys]]
#  item = "My SSH Key"
#  vault = "My Custom Vault"
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can test the result by running:
#
#  SSH_AUTH_SOCK=~/.1password/agent.sock ssh-add -l
#
# More examples can be found here:
#  https://developer.1password.com/docs/ssh/agent/config
[[ssh-keys]]
vault = "ydqtet743mjbloqnmwewyqfkom" # Private
account = "LZDNXBQM7FA4JIUZ3WNDLVIN2E" # Personal account

[[ssh-keys]]
vault = "jnd5jn2vgdwbnxvek7qa6mzg2q" # Employee
account = "62RN72VUIJHHLFBUJBYKN5VEBQ" # Work account
