"$schema" = 'https://starship.rs/config-schema.json'

right_format = '$status'

[directory]
#truncation_symbol = '…/'

[directory.substitutions]
'E:/Users/adamh' = '(E:) ~'
'F:/Users/adamh' = '(F:) ~'
'G:/Users/adamh' = '(G:) ~'

[cmd_duration]
format = '[$duration](bold yellow)'
# format = '⏱  [$duration](bold yellow)'

[direnv]
disabled = true

[gcloud]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
tag_disabled = false
tag_symbol = ' '

[git_metrics]
disabled = true

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = '⚠️'
ahead = '[⇡${count}](green)'
behind = '⇣${count}'
diverged = '[⇡${ahead_count}⇣${behind_count}](bold red)' # ⇕
up_to_date = ''
untracked = '[?${count}](bold red)'
stashed = '≡${count}'
modified = '~${count}'
staged = '[+${count}](green)'
renamed = '»${count}'
deleted = '[-${count}](bold red)'
typechanged = ''
style = 'bold yellow'
ignore_submodules = false

[status]
format = '[$symbol$status( $common_meaning)]($style)'
symbol = ''
pipestatus = true
disabled = false

[sudo]
disabled = false

