[directory]
#truncation_symbol = '…/'

[directory.substitutions]
'E:/Users/adamh' = '(E:) ~'
'F:/Users/adamh' = '(F:) ~'
'G:/Users/adamh' = '(G:) ~'

[status]
disabled = false

[git_status]
style = 'bold yellow'
ahead = '[⇡${count}](green)'
diverged = '[⇡${ahead_count}⇣${behind_count}](bold red)' # ⇕
behind = '⇣${count}'
staged = '[+${count}](green)'
modified = '~${count}'
deleted = '[-${count}](bold red)'
untracked = '[?${count}](bold red)'
renamed = '»${count}'
conflicted = '⚠️'
